services:
  teachme-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: teachme-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules